export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'
export const FETCH_PRODUCT_PROGRESS = 'FETCH_PRODUCT_PROGRESS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const INCREASE_COUNT = 'INCREASE_COUNT'

export const CHANGE_SCREEN = 'CHANGE_SCREEN'